'use client';

import { useState, useTransition } from 'react';
import { updateGameStatus, updateHackRoomMeta } from '@/lib/actions/hackroom';
import { useXpFeedback } from '@/components/Xp/XpFeedbackProvider';

interface Props { gameId: string; status: 'IN_PROGRESS' | 'COMPLETED' | 'DROPPED'; description: string | null; baseRomName: string | null; regionName: string | null; difficulty: string | null; }
export default function InfoCard({ gameId, status: initialStatus, description, baseRomName, regionName, difficulty }: Props) {
  const [editing, setEditing] = useState(false); const [status, setStatus] = useState(initialStatus); const [pending, startTransition] = useTransition(); const { showFeedback } = useXpFeedback();
  const labels: Record<string, string> = { IN_PROGRESS: 'Em andamento', COMPLETED: 'Concluída', DROPPED: 'Abandonada' };
  return <section className="rounded-3xl border border-cyan-300/20 bg-slate-950/65 p-5 shadow-[0_0_35px_rgba(34,211,238,.08)] backdrop-blur">
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="font-display text-[10px] font-bold uppercase tracking-[.22em] text-cyan-200/75">Ficha da hackroom</p><h2 className="mt-1 text-xl font-black text-white">Informações do projeto</h2></div><button type="button" onClick={() => setEditing(!editing)} className="rounded-xl border border-cyan-300/30 px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-cyan-100 hover:bg-cyan-300/10">{editing ? 'Fechar edição' : 'Editar'}</button></div>
    <div className="mb-5 flex items-center gap-2"><span className="text-xs text-white/55">Status</span><select value={status} disabled={pending} onChange={(e) => { const next = e.target.value as Props['status']; setStatus(next); startTransition(async () => { const result = await updateGameStatus(gameId, next); if (result.xp) showFeedback(result.xp, 'Jogo concluído'); }); }} className="rounded-lg border border-amber-300/25 bg-slate-900 px-2 py-1 text-xs font-bold text-amber-100"><option value="IN_PROGRESS">{labels.IN_PROGRESS}</option><option value="COMPLETED">{labels.COMPLETED}</option><option value="DROPPED">{labels.DROPPED}</option></select></div>
    {editing ? <form action={async (fd) => { await updateHackRoomMeta(fd); setEditing(false); }} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="gameId" value={gameId} /><Field name="baseRomName" label="ROM base" defaultValue={baseRomName} /><Field name="regionName" label="Região" defaultValue={regionName} /><label className="text-xs text-cyan-100/75">Dificuldade<select name="difficulty" defaultValue={difficulty ?? ''} className="mt-1 w-full rounded-lg border border-white/15 bg-slate-900 p-2 text-white"><option value="">Não definida</option><option value="EASY">Fácil</option><option value="NORMAL">Normal</option><option value="HARD">Difícil</option><option value="BRUTAL">Brutal</option></select></label><label className="text-xs text-cyan-100/75 sm:col-span-2">Descrição<textarea name="description" defaultValue={description ?? ''} className="mt-1 min-h-24 w-full rounded-lg border border-white/15 bg-slate-900 p-2 text-white" /></label><button className="sm:col-span-2 rounded-xl bg-cyan-300 px-4 py-2 text-xs font-black uppercase tracking-wider text-slate-950">Salvar ficha</button></form> : <dl className="grid gap-4 text-sm sm:grid-cols-3"><Datum label="ROM base" value={baseRomName} /><Datum label="Região" value={regionName} /><Datum label="Dificuldade" value={difficulty ? ({ EASY: 'Fácil', NORMAL: 'Normal', HARD: 'Difícil', BRUTAL: 'Brutal' }[difficulty] ?? difficulty) : null} /><div className="sm:col-span-3"><dt className="text-[10px] font-bold uppercase tracking-wider text-cyan-200/60">Descrição</dt><dd className="mt-1 whitespace-pre-wrap text-white/75">{description || 'Sem descrição ainda.'}</dd></div></dl>}
  </section>;
}
function Field({ name, label, defaultValue }: { name: string; label: string; defaultValue: string | null }) { return <label className="text-xs text-cyan-100/75">{label}<input name={name} defaultValue={defaultValue ?? ''} className="mt-1 w-full rounded-lg border border-white/15 bg-slate-900 p-2 text-white" /></label>; }
function Datum({ label, value }: { label: string; value: string | null }) { return <div><dt className="text-[10px] font-bold uppercase tracking-wider text-cyan-200/60">{label}</dt><dd className="mt-1 font-semibold text-white/85">{value || '—'}</dd></div>; }
